# Generated by Django 4.2.18 on 2025-05-12 20:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('community_discussion', '0002_rename_category_subcategory_catergory_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subcategory',
            old_name='catergory',
            new_name='category',
        ),
    ]
